---
name: minio-dist-deploy
director_uuid: 63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79

releases:
- name: minio
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.0.0/28
    reserved: [10.244.0.1]
    static: [10.244.0.2,10.244.0.3,10.244.0.4,10.244.0.5]
    cloud_properties:
      name: random

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  serial: false

jobs:
- name: minio-server
  templates:
  - name: minio-server
  instances: 4
  resource_pool: default
  persistent_disk: 10000
  networks:
  - name: default
    static_ips:
    - 10.244.0.2
    - 10.244.0.3
    - 10.244.0.4
    - 10.244.0.5
  properties:
    credential:
      accesskey: minio
      secretkey: minio123
    region: us-east-1
    port: 9001
